# Python Data Analysis Assignment 1

## Data Analysis Using NumPy and Pandas

### Objective
To practice numerical calculations and data manipulation using NumPy and Pandas.

### Topics Covered
- NumPy arrays, indexing, slicing, and statistical calculations
- Pandas Series creation, indexing, filtering, and manipulation
- Pandas DataFrame exploration, filtering, grouping, and modification

In [33]:
# Import required libraries
import numpy as np
import pandas as pd

# Display library versions
print("NumPy version:", np.__version__)
print("Pandas version:", pd.__version__)

NumPy version: 2.5.3
Pandas version: 3.0.6

In [32]:
# Week 1: Daily average temperatures in Celsius
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

print(temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]

In [5]:
# Inspect the properties of the Week 1 temperature array

print("Shape:", temperatures_w1.shape)
print("Data type:", temperatures_w1.dtype)
print("Number of elements:", temperatures_w1.size)

Shape: (7,)
Data type: float64
Number of elements: 7

In [6]:
# Convert Celsius to Fahrenheit
temperatures_w1_f = (temperatures_w1 * 9/5) + 32

print("Temperatures in Fahrenheit:", temperatures_w1_f)

Temperatures in Fahrenheit: [72.5  77.54 69.44 74.12 78.98 76.64 71.42]

In [7]:
# Find maximum, minimum, and mean temperatures

print("Maximum temperature:", np.max(temperatures_w1), "°C")
print("Minimum temperature:", np.min(temperatures_w1), "°C")
print("Mean temperature:", np.mean(temperatures_w1), "°C")

Maximum temperature: 26.1 °C
Minimum temperature: 20.8 °C
Mean temperature: 23.542857142857144 °C

In [8]:
# First three days of the week
print(temperatures_w1[:3])

[22.5 25.3 20.8]

In [9]:
# Weekend temperatures: last two days
print(temperatures_w1[-2:])

[24.8 21.9]

In [10]:
# Middle three days of the week
print(temperatures_w1[2:5])

[20.8 23.4 26.1]

In [11]:
# Create a 2D array for two weeks of temperatures

temperatures = np.array([
    [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
    [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
])

print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]

In [12]:
# Inspect the 2D temperature array

print("Shape:", temperatures.shape)
print("Data type:", temperatures.dtype)
print("Total number of elements:", temperatures.size)

Shape: (2, 7)
Data type: float64
Total number of elements: 14

In [13]:
# Extract temperatures for each week

print("Week 1 temperatures:", temperatures[0])
print("Week 2 temperatures:", temperatures[1])

Week 1 temperatures: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2 temperatures: [19.2 22.5 21.3 24.  23.5 22.8 20.1]

In [14]:
# Extract weekend temperatures for both weeks

print("Week 1 weekend:", temperatures[0, -2:])
print("Week 2 weekend:", temperatures[1, -2:])

Week 1 weekend: [24.8 21.9]
Week 2 weekend: [22.8 20.1]

In [15]:
# Create a Pandas Series with custom index labels

marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

In [16]:
# 1. Access the 1st rank student using integer position
print("1st rank mark:", marks.iloc[0])

# 2. Retrieve the top 3 ranks using index labels
print("\nTop 3 ranks:")
print(marks.loc[['Rank1', 'Rank2', 'Rank3']])

# 3. Retrieve the 3rd rank student's mark using iloc
print("\n3rd rank mark:", marks.iloc[2])

# 4. Filter ranks where marks are greater than 90
print("\nRanks with marks greater than 90:")
print(marks[marks > 90])

1st rank mark: 95

Top 3 ranks:
Rank1    95
Rank2    92
Rank3    89
dtype: int64

3rd rank mark: 89

Ranks with marks greater than 90:
Rank1    95
Rank2    92
dtype: int64

In [17]:
# 1. Change the 1st rank student's mark to 100
marks.loc['Rank1'] = 100

print("After updating Rank1:")
print(marks)

# 2. Remove the last rank (Rank5)
marks = marks.drop('Rank5')

print("\nAfter removing Rank5:")
print(marks)

# 3. Calculate CGPA by dividing each mark by 10
cgpa = marks / 10

print("\nCGPA:")
print(cgpa)

After updating Rank1:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

After removing Rank5:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

CGPA:
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64

In [18]:
# Import pandas if you have not already imported it
import pandas as pd

# Create the transactions DataFrame
transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],

    'ProductCategory': [
        'Electronics', 'Clothing', 'Electronics', 'Furniture',
        'Clothing', 'Electronics', 'Furniture', 'Clothing',
        'Furniture', 'Electronics'
    ],

    'Region': [
        'North', 'South', 'North', 'East', 'West',
        'North', 'East', 'West', 'South', 'North'
    ],

    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

# Display the DataFrame
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [19]:
# Display the complete DataFrame
display(transactions)

# Display the first 5 rows
print("First 5 rows:")
display(transactions.head())

# Display the last 5 rows
print("Last 5 rows:")
display(transactions.tail())

# Display the shape
print("Shape:", transactions.shape)

# Display column names
print("Column names:", transactions.columns.tolist())

# Display data types
print("Data types:")
print(transactions.dtypes)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

First 5 rows:

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

Last 5 rows:

   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

Shape: (10, 4)
Column names: ['TransactionID', 'ProductCategory', 'Region', 'Amount']
Data types:
TransactionID      int64
ProductCategory      str
Region               str
Amount             int64
dtype: object

In [20]:
transactions[['ProductCategory', 'Amount']]

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

In [21]:
transactions.iloc[:, -3:]

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

In [22]:
transactions[
    (transactions['Region'] == 'North') &
    (transactions['Amount'] > 200)
]

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

In [23]:
transactions['ProductCategory'].value_counts()

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

In [24]:
transactions['Region'].unique()

<StringArray>
['North', 'South', 'East', 'West']
Length: 4, dtype: str

In [25]:
transactions.groupby('Region')['Amount'].mean()

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

In [26]:
# Update the Amount to 165 for TransactionID 102
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165

# Display the updated transaction
display(transactions[transactions['TransactionID'] == 102])

   TransactionID ProductCategory Region  Amount
1            102        Clothing  South     165

In [27]:
# Calculate a 10% discount for each transaction
transactions['Discount'] = transactions['Amount'] * 0.10

# Display the DataFrame
display(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0

In [28]:
# Remove TransactionID 109
transactions = transactions[transactions['TransactionID'] != 109]

# Display the updated DataFrame
display(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [29]:
# Delete the Discount column
transactions = transactions.drop(columns=['Discount'])

# Display the final DataFrame
display(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400

In [30]:
# Final verification
print("NumPy 1D array shape:", temperatures_w1.shape)
print("NumPy 2D array shape:", temperatures.shape)

print("\nPandas Series:")
print(marks)

print("\nFinal Transactions DataFrame:")
display(transactions)

print("\nFinal DataFrame shape:", transactions.shape)
print("Final column names:", transactions.columns.tolist())

NumPy 1D array shape: (7,)
NumPy 2D array shape: (2, 7)

Pandas Series:
Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

Final Transactions DataFrame:

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400

Final DataFrame shape: (9, 4)
Final column names: ['TransactionID', 'ProductCategory', 'Region', 'Amount']